tasks:
  - before: echo "alias potigol='java -jar /workspace/beecrowd/bin/potigol.jar 2> /dev/null'" >> ~/.bashrc ; clear
    command: source ~/.bashrc ; clear

vscode:
  extensions:
    - potigol.potigol-language
